---
settings:
  name: StorageGRID
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di StorageGRID
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Cosa c'è di nuovo
      url: "/whats-new.html"
    - title: Problemi noti
      url: "/reference-known-issues.html"
  - title: Iniziare
    entries:
    - title: Scopri i sistemi StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gestire i sistemi StorageGRID
    entries:
    - title: Visualizza i tuoi sistemi StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Visualizza e aggiorna i certificati StorageGRID
      url: "/task-manage-certificates.html"
    - title: Gestire StorageGRID utilizzando la vista avanzata
      url: "/task-administer-storagegrid.html"
    - title: Utilizzare i servizi dati NetApp con StorageGRID
      url: "/task-enable-data-services.html"
    - title: Rimuovere un sistema
      url: "/task-remove-storagegrid.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere supporto
      url: "/task-support-registration.html"
    - title: Ottieni aiuto
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
